spring:
  application:
    name: apollo-configservice
  profiles:
    active: ${apollo_profile}
  datasource:
    url: jdbc:mysql://192.168.1.249:3306/ApolloConfigDB?characterEncoding=utf8
    username: root
    password: 1234567

ctrip:
  appid: 100003171

server:
  port: 8080

#logging:
#  file: /opt/logs/100003171/apollo-configservice.log
